---@class UiThemeData
---@field primary string
---@field secondary string

---@class MouseClickData
---@field x number
---@field y number
---@field button number
---@field istouch boolean
---@field pressed boolean
---@field release boolean
